### ISSUE TITLE
How does it compare to Tampermonkey/GreaseMonkey ?

### ISSUE THREAD

**Issue by FGRibreau** [dcohenb/WebOverride#2]
I'm curious, how WebOverride compares to Tampermonkey/GreaseMonkey ?

**Comment by dcohenb** [comment]
The idea is similar but the experience is a lot more friendly.
In Web override i try to keep it simple and it seems to work,
also, using external libs is much easier using the cdnjs.com libraries.
give it a try and you'll see

**Comment by FGRibreau** [comment]
Ok thanks @dcohenb :)
